name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  NODE24: '24.9.0'
  NODE22: '22.20.0'
  NODE20: '20.19.5'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  node24:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: ${{ env.NODE24 }}
          tags: 24.9,24,latest
          platform: linux/amd64,linux/arm64
  node22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: ${{ env.NODE22 }}
          tags: 22.20,22
          platform: linux/amd64,linux/arm64
  node20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE20 }}
        tags: 20.19,20
        platform: linux/amd64,linux/arm64
  node24-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: ${{ env.NODE24 }}
          tags: 24.9-dev,24-dev,dev
          dev: 1
          platform: linux/amd64,linux/arm64
  node22-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: ${{ env.NODE22 }}
          tags: 22.20-dev,22-dev
          dev: 1
          platform: linux/amd64,linux/arm64
  node20-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE20 }}
        tags: 20.19-dev,20-dev
        dev: 1
        platform: linux/amd64,linux/arm64
